name: Deploy .NET Backend to Beanstalk

on:
  push:
    paths:
      - "backend/CineNiche/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Publish .NET App
        run: |
          cd backend/CineNiche
          dotnet publish -c Release -o out
          cd out
          zip -r ../deploy.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: CineNicheProd
          environment_name: CineNicheProd-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: backend/CineNiche/deploy.zip
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
